name: Build, Test and Upload game.

on:
  push:
    branches: [ 'main' ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions: 
      contents: read

    steps:
      # downloads the github repo
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # Runs all the unit tests
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run tests with gradle wrapper
        working-directory: ./game
        run: ./gradlew test
      
      # Builds the game and runs the test report
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with gradle wrapper
        working-directory: ./game
        run: ./gradlew build jacocoTestReport

      # Uploads a test report
      - name: Upload the Jacoco coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-test-report
          path: game/headless/build/reports/jacoco/test/html/

      # Uploads the JAR file
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: lib.jar
          path: game/lwjgl3/build/libs/ENG1-1.0.0.jar

  release:
    name: release-version
    runs-on: ubuntu-latest
    needs: ["build"]
    if: startsWith(github.ref, 'refs/tags/')
    
    permissions:
      contents: write
    
    steps:
      # Fetch the jar file produced
    - name: Download jar file
      uses: actions/download-artifact@v4
      with:
        name: lib.jar
    - name: Display file structure
      run: ls
  
    - name: release
      uses: softprops/action-gh-release@v2
      with:
        files: lib.jar




      

  