name: Build, Test and Upload game.

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: 
      contents: read

    steps:
      # downloads the github repo
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # Runs all the unit tests
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run tests with gradle wrapper
        working-directory: ./game
        run: ./gradlew test
      
      # Builds the game and runs the test report
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with gradle wrapper
        working-directory: ./game
        run: ./gradlew build jacocoTestReport

      # Uploads a test report
      - name: Upload the Jacoco coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-test-report
          path: game/headless/build/reports/jacoco/test/html/

      # Uploads the JAR file
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: game/headless/build/reports/jacoco/test/html/

  