name: CI Run All Tests

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: 
      contents: read

    steps:
      # downloads the github repo
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with gradle wrapper
        working-directory: ./game
        run: ./gradlew build
  
  #test:
   # name: Run-Unit-Tests
    #runs-on: ubuntu-latest

    #steps:
      # downloads the github repo
    #  - name: Checkout repo
     #   uses: actions/checkout@v4

      #- name: Setup Java
       # uses: actions/setup-java@v4
        #with:
         # distribution: "temurin"
          #java-version: "17"
      
      #- name: Setup Gradle
       # uses: gradle/actions/setup-gradle@v4